/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-app-selector.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

/**
 * `etools-app-selector`
 *
 * App selector menu
 */
declare class EtoolsAppSelector extends PolymerElement {
  baseSite: string|null|undefined;

  /**
   * Class name toggle variable.
   * Used for styling when dropdown open/closed
   */
  opened: string|null|undefined;
  ready(): void;
  connectedCallback(): void;

  /**
   * Toggles the menu opened and closed
   */
  toggleMenu(): void;

  /**
   * Navigate window to path if ctrl/command are not pressed
   */
  manageClickEvent(e: any, path: any): void;

  /**
   * Change location to target app url found in menuOptions array items.
   * Url prop of item should just be app name
   *
   * Example:
   *
   *  `app.url="admin" will change location to 'http://myBaseUrlAndPort/admin/' `
   */
  goToPage(e: any): void;

  /**
   * Determine if click is outside of menu, close if true
   */
  _onCaptureClick(e: any): void;
  _isInPath(path: any, prop: any, value: any): any;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-app-selector": EtoolsAppSelector;
  }
}
